import type {Metadata} from 'next';
import Link from '@/components/StaticLink';
import {PageHeading, Arrow, GalleryStrip} from '@/components/Shared';
import IgReels from '@/components/IgReels';
import {copy,site} from '@/content/site';
import {igReelsAbout} from '@/content/ig';
// 旧站 /about-us/(近 3 个月 1 万次曝光,标题含 Authentic Ramen & Sushi Restaurant in Midtown NYC)跳到这里:标题带上同样的词,正文补回旧页的「Why guests love」一段
export const metadata:Metadata={title:{absolute:'About Zen: Ramen and Sushi Restaurant in Midtown NYC'},description:'About Zen Ramen & Sushi, an authentic ramen and sushi restaurant in Midtown Manhattan near Penn Station, Koreatown, Bryant Park and Madison Square Garden.',alternates:{canonical:'/about/'}};
export default function About(){return <main id="main"><PageHeading label="JAPANESE ROOTS. NEW YORK SOUL." title="A little more Zen"/><section className="about-story container"><img src="/images/shot-about-tonkotsu-square.webp" width="1280" height="1280" alt="Tonkotsu ramen with braised pork belly, soft eggs, corn and arugula in a black bowl"/><div><p className="eyebrow red">ABOUT ZEN RAMEN & SUSHI</p><h2>Comfort food.<br/>At the heart of it all.</h2><p>{copy.about}</p><p>{copy.aboutSecond}</p><a href={site.reserve} target="_blank" rel="noopener noreferrer" className="button button-red">RESERVE A TABLE <Arrow/></a></div></section><section className="about-details container"><div><p className="eyebrow red">FROM OUR KITCHEN</p><h2>Ramen & sushi.<br/>Made with care.</h2><p>{copy.ramen}</p><p>{copy.sushi}</p><Link href="/menu/" className="text-link">EXPLORE THE MENU <Arrow/></Link></div><img src="/images/shot-sashimi-box.webp" width="1536" height="1024" loading="lazy" alt="A wooden box of salmon, tuna and yellowtail sashimi with sushi rolls"/></section><section className="about-more container"><h2>Something for everyone.</h2><p>Our menu features rich, slow-simmered Tonkotsu Ramen, flavorful Shoyu Ramen, spicy ramen, handcrafted sushi rolls, fresh sashimi, poke bowls, rice dishes, and Japanese appetizers. Every dish is prepared with quality ingredients to deliver the authentic flavors our guests come back for.</p><p>Whether you’re stopping in for a quick lunch, enjoying dinner before a concert at Madison Square Garden, meeting friends after work, or ordering takeout, Zen Ramen & Sushi offers a welcoming atmosphere and consistently delicious food.</p><div className="about-feature-list"><span>Fresh sushi rolls & sashimi</span><span>Rice bowls & Japanese appetizers</span><span>Lunch specials</span><span>Happy Hour</span><span>Vegetarian options</span><span>Takeout & delivery</span><span>Catering for offices & events</span></div><p>Our convenient Midtown location makes us an easy choice for office workers, tourists, students, and locals looking for quality ramen and sushi near Penn Station and Koreatown on 32nd street.</p><p>Whether it’s your first visit or you’re one of our regular guests, we’re committed to serving fresh ingredients, authentic flavors, and a memorable dining experience every time.</p><h2>Why guests love Zen Ramen & Sushi.</h2><div className="about-feature-list"><span>Slow-cooked Tonkotsu ramen broth</span><span>Fresh sushi prepared daily</span><span>Convenient location near Penn Station</span><span>Weekday lunch specials</span><span>Happy Hour food and drink specials</span><span>Fast takeout and delivery</span><span>Before Knicks games, concerts & shows</span></div></section><IgReels reels={igReelsAbout} variant="rail" eyebrow="SEE IT IN MOTION" title={<>A taste of the everyday.</>}/><GalleryStrip/></main>;}
