import Ico from '@/components/Ico';
import Intro from '@/components/Intro';
import Link from '@/components/StaticLink';
import type { Metadata } from 'next';
import { site, copy } from '@/content/site';
import { Arrow, GalleryStrip } from '@/components/Shared';
import LocationMap from '@/components/LocationMap';
import IgReels from '@/components/IgReels';
import HomeFilm from '@/components/HomeFilm';
import OpenStatus from '@/components/OpenStatus';
export const metadata: Metadata = {alternates:{canonical:'/'},openGraph:{title:'Zen Ramen & Sushi',description:copy.hero,url:'/',siteName:'Zen Ramen & Sushi',type:'website',locale:'en_US',images:[{url:'/images/shot-og.webp',width:1200,height:630,alt:'Ramen and sushi at Zen Ramen & Sushi in Midtown Manhattan'}]}};
export default function Home(){return <><Intro/><main id="main">
  <section className="hero">
    <div className="hero-copy"><h1><span className="h1-kicker"><span className="red-dot"/> Japanese Comfort Food{' '}· <span style={{whiteSpace:'nowrap'}}>Midtown Manhattan</span></span>AUTHENTIC<br/>RAMEN<br/><span>& SUSHI.</span></h1><p className="hero-description">{copy.hero}</p><OpenStatus/><div className="hero-actions"><a href={site.order} className="button button-red" data-cta="hero-order" target="_blank" rel="noopener noreferrer">ORDER ONLINE <Arrow/></a><a href={site.reserve} className="text-link" data-cta="hero-reserve" target="_blank" rel="noopener noreferrer">RESERVE A TABLE <Arrow/></a></div><div className="hero-quick-links"><a href={site.phoneHref} data-cta="hero-call">CALL {site.phone}</a><a href={site.directions} data-cta="hero-directions" target="_blank" rel="noopener noreferrer">GET DIRECTIONS <Arrow/></a><Link href="/menu/" data-cta="hero-menu">SEE THE MENU <Arrow/></Link></div><a className="hero-reviews" href={site.reviews} data-cta="hero-reviews" target="_blank" rel="noopener noreferrer"><span className="stars" aria-hidden="true"><Ico n="star"/><Ico n="star"/><Ico n="star"/><Ico n="star"/><span className="star-half"><Ico n="star"/><Ico n="star"/></span></span>4.5 · 4,300+ Google reviews</a><div className="hero-footnote"><span className="tiny-cross"><Ico n="spark"/></span><span>RAMEN. SUSHI. A LITTLE ZEN.<br/><small>In the heart of Midtown Manhattan.</small></span></div></div>
    <div className="hero-photo"><img src="/images/shot-hero-noodle-chopsticks.webp" alt="Chopsticks lifting thick noodles from a bowl of grilled chicken noodle soup" width="1200" height="1600" fetchPriority="high"/><div className="hero-photo-shade"/><span className="hero-japanese" aria-hidden="true">らーめん</span><span className="photo-caption">SLOW-SIMMERED. FULL OF FLAVOR.</span><div className="hero-stamp"><span>150 W 36TH ST</span><strong>FIND<br/>YOUR ZEN</strong><span>NEW YORK, NY <Ico n="ne"/></span></div></div>
  </section>
  <div className="ticker" role="img" aria-label="Ramen, sushi, sake, good times"><div aria-hidden="true"><span className="ticker-run">RAMEN <span><Ico n="spark"/></span> SUSHI <span><Ico n="spark"/></span> SAKE <span><Ico n="spark"/></span> GOOD TIMES <span><Ico n="spark"/></span> RAMEN <span><Ico n="spark"/></span> SUSHI <span><Ico n="spark"/></span> SAKE <span><Ico n="spark"/></span> GOOD TIMES <span><Ico n="spark"/></span> RAMEN <span><Ico n="spark"/></span> SUSHI <span><Ico n="spark"/></span> SAKE <span><Ico n="spark"/></span> GOOD TIMES <span><Ico n="spark"/></span> RAMEN <span><Ico n="spark"/></span> SUSHI <span><Ico n="spark"/></span> SAKE <span><Ico n="spark"/></span> GOOD TIMES <span><Ico n="spark"/></span></span><span className="ticker-run">RAMEN <span><Ico n="spark"/></span> SUSHI <span><Ico n="spark"/></span> SAKE <span><Ico n="spark"/></span> GOOD TIMES <span><Ico n="spark"/></span> RAMEN <span><Ico n="spark"/></span> SUSHI <span><Ico n="spark"/></span> SAKE <span><Ico n="spark"/></span> GOOD TIMES <span><Ico n="spark"/></span> RAMEN <span><Ico n="spark"/></span> SUSHI <span><Ico n="spark"/></span> SAKE <span><Ico n="spark"/></span> GOOD TIMES <span><Ico n="spark"/></span> RAMEN <span><Ico n="spark"/></span> SUSHI <span><Ico n="spark"/></span> SAKE <span><Ico n="spark"/></span> GOOD TIMES <span><Ico n="spark"/></span></span></div></div>
  <HomeFilm/>
  <section className="location-section container" id="hours-location"><div className="section-heading"><div><p className="eyebrow red">HOURS & LOCATION</p><h2>Your Midtown<br/>meet-up spot.</h2></div><p className="section-description">{copy.location}</p></div><div className="location-card"><div className="location-info"><span className="location-tag">ONE LITTLE CORNER OF NYC</span><h3>Come on in.</h3><p className="address">150 W 36th St<br/>New York, NY 10018</p><a className="phone" href={site.phoneHref}>{site.phone} <Arrow/></a><div className="hours">{site.hours.map(h=><div key={h.days}><span>{h.days}</span><span>{h.time}</span></div>)}</div><a href={site.directions} className="button button-dark" target="_blank" rel="noopener noreferrer">GET DIRECTIONS <Arrow/></a></div><LocationMap/></div></section>
  <section className="menu-preview container"><div className="section-heading"><div><p className="eyebrow red">OUR MENU</p><h2>Something for<br/>every craving.</h2></div><div className="section-actions"><a className="button button-red" href={site.order} data-cta="menu-order" target="_blank" rel="noopener noreferrer">ORDER ONLINE <Arrow/></a><Link className="text-link" href="/menu/" data-cta="menu-viewall">VIEW THE FULL MENU <Arrow/></Link></div></div><div className="menu-cards">{[{name:'Dinner',n:'01',src:'/images/shot-card-dinner-tonkotsu.webp',text:'Ramen, sushi & Japanese favorites',href:'dinner'},{name:'Lunch',n:'02',src:'/images/shot-card-lunch-sushi-box.webp',text:'Monday–Friday · 11:30 AM–4 PM · Except holidays',href:'lunch'},{name:'Happy Hour',n:'03',src:'/images/shot-card-happy-hour.webp',text:'4–8 PM · Appetizers, rolls & drinks',href:'happy-hour'}].map(c=><Link href={'/menu/#'+c.href} className="menu-card" key={c.name}><div className="menu-card-image"><img src={c.src} alt={c.name==='Happy Hour'?'A seared sushi roll and a pink martini on the happy hour menu':c.name==='Dinner'?'Tonkotsu ramen with pork belly, soft egg, corn and arugula':'A wooden box of sashimi and sushi rolls'} width="700" height="600" loading="lazy"/><span className="round-arrow"><Arrow/></span></div><h3>{c.name}</h3><p>{c.text}</p></Link>)}</div><p className="menu-small-note">Cash and card prices are listed on our full menu.</p></section>
  <section className="about-preview"><div className="about-image"><img src="/images/shot-about-tonkotsu.webp" alt="Tonkotsu ramen with braised pork belly, soft eggs, corn and arugula in a black bowl" width="1536" height="1024" loading="lazy"/><span aria-hidden="true">いただきます</span></div><div className="about-copy"><p className="eyebrow">ABOUT ZEN</p><h2>Japanese roots.<br/>New York soul.</h2><p>{copy.about}</p><p>{copy.homeVisit}</p><Link className="button button-cream" href="/about/">GET TO KNOW US <Arrow/></Link></div></section>
  <section className="catering-preview container"><div className="catering-copy"><p className="eyebrow red">EVENTS & CATERING</p><h2>Good things<br/>are better{' '}<br/><span className="red">shared.</span></h2><p>{copy.catering}</p><Link className="button button-dark" href="/events-catering/">PLAN YOUR EVENT <Arrow/></Link></div><div className="catering-image"><img src="/images/shot-shared-table.webp" srcSet="/images/shot-shared-table-sm.webp 819w, /images/shot-shared-table.webp 1600w" sizes="(max-width: 650px) 87vw, (max-width: 1655px) 44vw, 730px" alt="Ramen, sushi rolls and an iced drink shared across one table" width="1600" height="2000" loading="lazy"/><span className="catering-tag">FOR YOUR NEXT GET-TOGETHER <Ico n="spark"/></span></div></section>
  <GalleryStrip/>
  <IgReels/>
</main></>;}
