import Intro from '@/components/Intro';
import Link from '@/components/StaticLink';
import type { Metadata } from 'next';
import { site, copy } from '@/content/site';
import { Arrow, GalleryStrip } from '@/components/Shared';
import LocationMap from '@/components/LocationMap';
export const metadata: Metadata = {alternates:{canonical:'/'},openGraph:{title:'Zen Ramen & Sushi',description:copy.hero,url:'/',images:['/images/photo-10.webp']}};
export default function Home(){return <><Intro/><main id="main">
  <section className="hero">
    <div className="hero-copy"><h1><span className="h1-kicker"><span className="red-dot"/> Japanese Comfort Food · Midtown Manhattan</span>AUTHENTIC<br/>RAMEN<br/><span>& SUSHI.</span></h1><p className="hero-description">{copy.hero}</p><div className="hero-actions"><Link href="/menu/" className="button button-red">EXPLORE OUR MENU <Arrow/></Link><a href={site.reserve} className="text-link" target="_blank" rel="noopener noreferrer">RESERVE A TABLE <Arrow/></a></div><a className="hero-reviews" href={site.directions} target="_blank" rel="noopener noreferrer"><span className="stars" aria-hidden="true">★★★★<span className="star-half">★</span></span>4.5 · 4,300+ Google reviews</a><div className="hero-footnote"><span className="tiny-cross">✳</span><span>RAMEN. SUSHI. A LITTLE ZEN.<br/><small>In the heart of Midtown Manhattan.</small></span></div></div>
    <div className="hero-photo"><img src="/images/photo-10.webp" alt="Chopsticks lifting fresh noodles from a steaming bowl of ramen" width="768" height="1024" fetchPriority="high"/><div className="hero-photo-shade"/><span className="hero-japanese" aria-hidden="true">らーめん</span><span className="photo-caption">SLOW-SIMMERED. FULL OF FLAVOR.</span><div className="hero-stamp"><span>150 W 36TH ST</span><strong>FIND<br/>YOUR ZEN</strong><span>NEW YORK, NY ↗</span></div></div>
  </section>
  <div className="ticker" role="img" aria-label="Ramen, sushi, sake, good times"><div aria-hidden="true"><span className="ticker-run">RAMEN <span>✳</span> SUSHI <span>✳</span> SAKE <span>✳</span> GOOD TIMES <span>✳</span> RAMEN <span>✳</span> SUSHI <span>✳</span> SAKE <span>✳</span> GOOD TIMES <span>✳</span></span><span className="ticker-run">RAMEN <span>✳</span> SUSHI <span>✳</span> SAKE <span>✳</span> GOOD TIMES <span>✳</span> RAMEN <span>✳</span> SUSHI <span>✳</span> SAKE <span>✳</span> GOOD TIMES <span>✳</span></span></div></div>
  <section className="location-section container" id="hours-location"><div className="section-heading"><div><p className="eyebrow red">HOURS & LOCATION</p><h2>Your Midtown<br/>meet-up spot.</h2></div><p className="section-description">{copy.location}</p></div><div className="location-card"><div className="location-info"><span className="location-tag">ONE LITTLE CORNER OF NYC</span><h3>Come on in.</h3><p className="address">150 W 36th St<br/>New York, NY 10018</p><a className="phone" href={site.phoneHref}>{site.phone} <Arrow/></a><div className="hours">{site.hours.map(h=><div key={h.days}><span>{h.days}</span><span>{h.time}</span></div>)}</div><a href={site.directions} className="button button-dark" target="_blank" rel="noopener noreferrer">GET DIRECTIONS <Arrow/></a></div><LocationMap/></div></section>
  <section className="menu-preview container"><div className="section-heading"><div><p className="eyebrow red">OUR MENU</p><h2>Something for<br/>every craving.</h2></div><Link className="text-link" href="/menu/">VIEW THE FULL MENU <Arrow/></Link></div><div className="menu-cards">{[{name:'Dinner',n:'01',src:'/images/dish-tonkotsu-shoyu.webp',text:'Ramen, sushi & Japanese favorites',href:'dinner'},{name:'Lunch',n:'02',src:'/images/dish-lunch-sushi.webp',text:'Monday–Friday · 11:30 AM–4 PM · Except holidays',href:'lunch'},{name:'Happy Hour',n:'03',src:'/images/zen-happy-hour-card.webp',text:'4–8 PM · Appetizers, rolls & drinks',href:'happy-hour'}].map(c=><Link href={'/menu/#'+c.href} className="menu-card" key={c.name}><div className="menu-card-image"><img src={c.src} alt={c.name==='Happy Hour'?'Draft beer and izakaya small plates during happy hour':c.text} width="700" height="600" loading="lazy"/><span className="round-arrow"><Arrow/></span></div><h3>{c.name}</h3><p>{c.text}</p></Link>)}</div><p className="menu-small-note">Cash and card prices are listed on our full menu.</p></section>
  <section className="about-preview"><div className="about-image"><img src="/images/photo-0.webp" alt="Japanese ramen with pork, noodles and a rich broth" width="1024" height="683" loading="lazy"/><span aria-hidden="true">いただきます</span></div><div className="about-copy"><p className="eyebrow">ABOUT ZEN</p><h2>Japanese roots.<br/>New York soul.</h2><p>{copy.about}</p><Link className="button button-cream" href="/about/">GET TO KNOW US <Arrow/></Link></div></section>
  <section className="catering-preview container"><div className="catering-copy"><p className="eyebrow red">EVENTS & CATERING</p><h2>Good things<br/>are better<br/><span className="red">shared.</span></h2><p>{copy.catering}</p><Link className="button button-dark" href="/events-catering/">PLAN YOUR EVENT <Arrow/></Link></div><div className="catering-image"><img src="/images/shared-table-original.jpg" srcSet="/images/photo-4.webp 819w, /images/shared-table-original.jpg 2665w" sizes="(max-width: 650px) 87vw, (max-width: 1655px) 44vw, 730px" alt="Japanese dishes arranged around a shared table, with chopsticks reaching for a bite" width="2665" height="3331" loading="lazy"/><span className="catering-tag">FOR YOUR NEXT GET-TOGETHER ✳</span></div></section>
  <GalleryStrip/>
</main></>;}
